### PR TITLE
Travis CI: Add the current version of Python

### PR DESCRIPTION
**Pull request by cclauss**
As discussed in nodejs/node-gyp#2525

@d3x0r Your review, please.

### CODE REVIEW

**Comment by cclauss** [comment]
https://docs.travis-ci.com/user/multi-os/ says that Mac should be `os: osx`

**Comment by d3x0r** [comment]
https://app.travis-ci.com/github/d3x0r/sack.vfs/jobs/543544284/config   didn't help; but I didn't add it so far up... 


https://app.travis-ci.com/github/d3x0r/sack.vfs/jobs/543544633/config   and still fails moving it up.

**Comment by d3x0r** [comment]
re mac - it works as it is...

**Comment by cclauss** [comment]
Please land the `script:` section (lines 48-51 of this PR) so we can see what Python is installed.

**Comment by cclauss** [comment]
Seem like Linux and macOS are now working but Windows is not.

For Windows, see the `choco` trick on `before_install:` at:
https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
```yaml
    - name: "Python 3.10.0 on Windows"
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.10.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python310:/c/Python310/Scripts:$PATH
```
https://community.chocolatey.org/packages/python/3.10.0

**Comment by cclauss** [comment]
https://github.com/nodejs/release#readme for current (and EOL) releases.

**Comment by d3x0r** [comment]
Okay choco before-install rule fixes windows, thank you much.
OOC - why mention end of life?   12's still valid for 6 more months :)

**Pull request closed without merging**
